version: '3'
services:
  mongo:
    image: mongo:4.2.1-bionic
    volumes:
      - database:/data/db
  api:
    build: .
    links:
      - mongo
    environment:
      - POPULATE_DB=true
    ports:
      - 8080:8080
volumes:
  database: