name: Tree Coding

on:
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        container:
            image: node:12
        
        services:
            mongo:
                image: mongo:4.2.1-bionic
        
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install Typescript
              run: npm install typescript -g
            - name: Install NPM packages
              run: npm install
            - name: Run Tests
              run: npm run test